ARSN-485: Fix broken CI ubuntu24 hotfix branch
Bump actions form v2 to v4 as setup-node has an error
```
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Error: Cache service responded with 422
```

(cherry picked from commit 19d913c420e62c12df3a94941fc9467c778df114)